### ISSUE TITLE
Setup simple deployment

### ISSUE THREAD

**Issue by domoritz** [vega/editor-backend#10]
See https://github.com/vega/editor/tree/server. I want to run this at vega.now.sh.

**Comment by algomaster99** [comment]
@domoritz How shall I configure it?

**Comment by domoritz** [comment]
What do you mean? I want you to set it up so that I have to run `yqrn deploy` and it just works.

**Comment by domoritz** [comment]
Or even better, set it up so we can deploy on tags from Travis.
