### ISSUE TITLE
Sign in does not work on Safari

### ISSUE THREAD

**Issue by domoritz** [vega/editor-backend#130]
Somehow, I cannot sign in on safari. After going through the login process on github, I don't get signed in on the editor.

**Comment by domoritz** [comment]
The issue is probably that we need to set cookies to be secure.

**Comment by domoritz** [comment]
I think we need to set https://github.com/vega/editor-backend/blob/master/src/app.ts#L77 but somehow I cannot log in anymore after I uncomment this line. 

@algomaster99 Can you help me here?

**Comment by algomaster99** [comment]
@domoritz what error are you getting?

**Comment by domoritz** [comment]
There seem to be two separate issues.

1) Chrome warns us about unsafe cookies. We should enable safe cookies (but when I do it, login doesn't work for some reason).
2) When I check whether I am logged in in Chrome in incognito or Safari (on my machine) the response is always that I am not logged in.

<img width="727" alt="Screen Shot 2020-02-15 at 19 04 53" src="https://user-images.githubusercontent.com/589034/74598417-189ad100-5026-11ea-8933-dca827302836.png">
<img width="1097" alt="Screen Shot 2020-02-15 at 19 05 03" src="https://user-images.githubusercontent.com/589034/74598418-1b95c180-5026-11ea-9326-1331c7301265.png">

Any idea what's going wrong? It looks like cors is not working as expected.

**Comment by algomaster99** [comment]
@domoritz Chrome in incognito works fine for me. For Safari, shall I just check it on some iPhone?

**Comment by domoritz** [comment]
I noticed that I can log in if I disable this setting to prevent cross-site tracking. 

<img width="886" alt="Screen Shot 2020-02-27 at 09 40 55" src="https://user-images.githubusercontent.com/589034/75470307-56142e00-5945-11ea-85fd-73e319b06faf.png">

Maybe let's focus on enabling safe cookies (https://github.com/vega/editor-backend/blob/master/src/app.ts#L77) for now and look at this issue later. Can you look into this?

**Comment by algomaster99** [comment]
@domoritz `secure: true` is only responsible for this behavior https://stackoverflow.com/a/40324493/11751642. What problem are you facing exactly?

**Comment by domoritz** [comment]
Adding the secure flag is for https://github.com/vega/editor-backend/issues/130#issuecomment-586409415

**Comment by algomaster99** [comment]
@domoritz 44ed9700ec30c88994e7605d5b2e321ae93c8fb4 fixes this.
Please note my comment there though.
