### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by algomaster99** [vega/editor-backend#17]
We can add favicon using [this link](https://github.com/vega/vega.github.io/blob/master/favicon.ico) but Express has different instructions to set it up. It suggests to install `serve-favicon` and have the `favicon.ico` file as a static file in the repository. Should we download it and keep at as an asset in the project?

**Comment by algomaster99** [comment]
@domoritz What do you suggest?

**Comment by domoritz** [comment]
We don't need a favicon for a backend service.
