### ISSUE TITLE
Replace now with vercel

### ISSUE THREAD

**Issue by ashu8912** [vega/editor-backend#237]
We have a dependency on now to build the backend but as stated in https://www.npmjs.com/package/now  it is deprecated  so if anything breaks in future because of now we wont have a update for it.

**Comment by domoritz** [comment]
Thank you for filing the issue. Can you send a pull request?

**Comment by ashu8912** [comment]
sure @domoritz

**Comment by domoritz** [comment]
Actually, it looks like I should do it to make sure the project is linked correctly.

**Comment by ashu8912** [comment]
cool i hope nothing breaks :stuck_out_tongue:
