### ISSUE TITLE
Sign-in link at https://vega.now.sh/ doesn't work

### ISSUE THREAD

**Issue by domoritz** [vega/editor-backend#35]
![Screen Shot 2019-08-25 at 7 57 14 AM](https://user-images.githubusercontent.com/589034/63651813-fb87e400-c70d-11e9-81ed-1a04b10ced4b.png)

**Comment by algomaster99** [comment]
@domoritz is this still broken? Working fine for me. I can't reproduce this.

**Comment by domoritz** [comment]
I get logged in but there is no redirect. Should we redirect to the main page?

**Comment by algomaster99** [comment]
@domoritz we are redirected to editor frontend on production. There is no redirection on development because `postMessage` is considered that way.

**Comment by domoritz** [comment]
When I go to https://vega.now.sh/auth/github, I get an error, though:

<img width="546" alt="Screen Shot 2019-09-15 at 16 47 54" src="https://user-images.githubusercontent.com/589034/64929247-a143e580-d7d8-11e9-9087-543371de0398.png">

**Comment by algomaster99** [comment]
@domoritz So I will tell you how this works actually. When the sign-in button is clicked on vega editor, this window becomes `window.opener`. And the authentication takes place in a new tab. After successful authentication, the browser tab is closed, and we are redirected back to the tab where the editor is opened.
Now this, JS has an event listener for recognising `postMessage` events. I check that if `type === 'auth'` or not, if former, I set state to show profile picture.

[This](https://github.com/vega/editor-backend/blob/49c4cab7edb8af9d768a8ad3ff3ef2c92077b3e3/src/controllers/auth.ts#L48) is the route which sends the following response. 
```
<html>
   <script>
     window.opener.postMessage(
       {type: "auth"}, "*"
     );
     window.close();
   </script>
</html>
```

Now when you are directly `GET`ing at `https://vega.now.sh/auth/github`, there is no such thing as `window.opener`.

**Comment by algomaster99** [comment]
@domoritz Should I think of a fix? Doesn't seem a big issue to me since one will sign in through front-end only.

**Comment by domoritz** [comment]
Either way. I think a simple redirect if window.opener doesn't exist would be nice.
