### ISSUE TITLE
Implementation of pagination

### ISSUE THREAD

**Issue by algomaster99** [vega/editor-backend#45]
## Overview
Pagination in GraphQL isn't done using page numbers like in a standard API endpoint which looks something like this: `https://example.com/?page=1`. In graphQL, we use cursor which a base64 encoded string or offset (this method is not available in octokit/grapql). Please read about these methods here - https://graphql.org/learn/pagination/#pagination-and-edges.
Therefore, we might need to resort to store cursors on front-end to paginate.

## Working
I will first explain what queries and its corresponding outputs mean.

### Input Query
```
{
  user(login: "algomaster99") {
    gists(first: 1, orderBy: {field: CREATED_AT, direction: DESC}) {
      edges {
        cursor
        node {
          name
          description
        }
      }
      pageInfo {
        startCursor
        hasPreviousPage
        endCursor
        hasNextPage
      }
      totalCount
    }
  }
}
```

### Output
```
{
  "data": {
    "user": {
      "gists": {
        "edges": [
          {
            "cursor": "Y3Vyc29yOnYyOpK5MjAxOS0wOC0zMFQwMToyNjo0NSswNTozMM4F17K9",
            "node": {
              "name": "19adeb7cfaffadeefda5b39a412f317c",
              "description": "Latest"
            }
          }
        ],
        "pageInfo": {
          "startCursor": "Y3Vyc29yOnYyOpK5MjAxOS0wOC0zMFQwMToyNjo0NSswNTozMM4F17K9",
          "hasPreviousPage": false,
          "endCursor": "Y3Vyc29yOnYyOpK5MjAxOS0wOC0zMFQwMToyNjo0NSswNTozMM4F17K9",
          "hasNextPage": true
        },
        "totalCount": 4
      }
    }
  }
}
```

### Explanation of output

- Edges: It is an array of all the gists fetched according to the condition (first: 1, orderBy: {field: CREATED_AT, direction: DESC}). Fetching of one gist is enforced by: `first: 1`
    - Cursor: This is a base64 encoded string which is, I think, a unique way to index gists.
    - Node: This is a gist object. The `name` and `description` attributes correspond to the ID and title of the gists.

- PageInfo: This gives the details about the pages.
    - Start cursor: Shows the cursor of the first gist.
    - End cursor: Shows the cursor of the last gist.
    - hasPreviousPage: Checks if there are any gist before the `startCursor`.
    - hasNextPage: Checks if there are any gists after the `endCursor`.

> All gists corresponding to cursors between `startCursor` and `endCursor` are displayed in `edges`.

- Total count: Shows the number of gists.

### Solution
To implement pagination, let us consider the following assumptions first:
- Number of gist in one page: 2 (I am taking my case specifically :sweat_smile:)

1. When we open the Gist modal on front-end, an initial request will be made to the back-end to get the following data:-
  - Total edges as an array of cursors.
  - First page data (the details of first two gists).
```
"edges": [
          {
            "cursor": "Y3Vyc29yOnYyOpK5MjAxOS0wOC0zMFQwMToyNjo0NSswNTozMM4F17K9",
            "node": {
              "name": "19adeb7cfaffadeefda5b39a412f317c",
              "description": "Latest",
              "files": [
                {
                  "name": "spec.json"
                }
              ]
            }
          },
          {
            "cursor": "Y3Vyc29yOnYyOpK5MjAxOS0wOC0yOFQxMjowNjoyOSswNTozMM4F1z-E",
            "node": {
              "name": "e5cf1cc1e12a40bc0a69cf77c934f239",
              "description": "It works so fine!",
              "files": [
                {
                  "name": "test.vl.json"
                }
              ]
            }
          },
          {
            "cursor": "Y3Vyc29yOnYyOpK5MjAxOS0wOC0yM1QwNzo1Mjo1OCswNTozMM4F1g8C",
            "node": {
              "name": "6ee25328dd6aa5c86476b0fa5d4a85b9",
              "description": "Google Summer of Code 2019 - Final Evaluation",
              "files": [
                {
                  "name": "GSOC19.md"
                }
              ]
            }
          },
          {
            "cursor": "Y3Vyc29yOnYyOpK5MjAxOC0xMi0xNVQyMTowNToxOSswNTozMM4FlBQJ",
            "node": {
              "name": "830edacfc6b36fcf5604332cf7b8cbc1",
              "description": "Key generation using RSA algorithm",
              "files": [
                {
                  "name": "key_generation.py"
                }
              ]
            }
          }
        ],
"totalCount": 4
```
- An array of all cursors will be sent.
- The ID, files, etc. of first two gists will be sent to display the information for the first page.

2. Since there are 4 gists in total, the pagination component will look like this:
| :arrow_left: | 1 (selected) | 2 | :arrow_right: |

3. Clicking on `2` will find the corresponding cursor from the array and send a request to back-end. For example, assume the array is as follows: `['1', '2', '3', '4']`. Since we have two gist on the first page, the second page will have the following two gist viz `3` and `4`. So the `nextCursor` will be `3`.

The query can look like this:
```
{
  user(login: "algomaster99") {
    gists(first: 2, after: "2" orderBy: {field: CREATED_AT, direction: DESC})
...
```
This will get `3` and `4`.

## One problem

The above solution works well for people who have 100 gist. `first` attribute in the query allows to fetch only 100 gists at a time. Therefore, we will have cursors for all 100 gists.

> Question Why getting all cursors are important?
If someone from 1st page goes to 103rd page (suppose), we will need the 206th cursor to get contents of that page.

**Comment by domoritz** [comment]
I think it makes sense to mirror how we do pagination in github as closely as possible in the frontend. This will simplify the logic of the backend service we are writing. Yes, we can store the cursors in the frontend to make it work. 

I think there are two ways for us build the UI in the frontend. Either, we just have a simple `load more...` link at the bottom or we actually build pagination with `<`, `>` and pages `1 | 2 | 3 ...`. I'll leave it up to you to decide what you prefer.
