### ISSUE TITLE
Choice of database

### ISSUE THREAD

**Issue by algomaster99** [vega/editor-backend#7]
We can search over the following things for vega and vega-lite visualization:-
- Description of the visualization it can be of the visualization or the gist.
- Type of graph
- Search a specific user's visualization

### Elasticsearch DB
- This DB doesn't support relations between any fields. One wouldn't be able to link user and its gist. This will be a problem when we are searching for visualization according to a user.
- It also doesn't have an updated ODM. Making search queries will be difficulty and be a little long. Current version of elasticsearch is `7.0.0` while its [ODM](https://www.npmjs.com/package/elasticsearch-odm-5) was updated a year ago for `5.0.0`.
- [This repository's file](https://github.com/enjalot/blockbuilder/blob/master/server.js) simply makes api calls to GitHub's api to retrieve a user and the clicked GistID.
- Searching can be performed like they have done in [this file](https://github.com/enjalot/blockbuilder-search/blob/master/index.js). The queries written in there are quite long to write. Also, it is good for textual search over random data. It can't search for visualization according to users. Our data is very organized and can be simply put in a schema.
- ElasticSearch does not provide any authentication or access control functionality.
- I think it would have been a good choice if had to just search over random texts.

### PostgreSQL vs. MongoDB
- They both are pretty good with MongoDB having a famous ODM called Mongoose.
- I am inclined towards MongoDB since it deals with JSON objects which need not be serialized before rendering it in an API view. Hence, shortening the process.
- Since our schema definition isn't really perfect for gists because we don't know yet what users would search over, MongoDB is a better choice since it stores document like data and doesn't necessarily require a predefined structure. So later on we can add more fields in a gist so that it can be easily  indexed and searched over.

**Comment by algomaster99** [comment]
@domoritz @siddhant1 I tried to research as much as possible but I would really like your suggestions on this.

**Comment by domoritz** [comment]
https://github.com/elastic/elasticsearch-js is an up-to-date library for Elasticsearch. I also found that you can [search over specific fields](https://www.elastic.co/guide/en/elasticsearch/reference/7.1/search-request-body.html).

One other issue we need to look into is ranking search results. As far as I can see it, Mongo or Postgres don't have a good way to rank search results. Github and Wikipedia are using Elasticsearch for searching. I see that Mongo or PG are a better fit for data storage but I'm not convinced that they make a better search index.

**Comment by algomaster99** [comment]
@domoritz Yeah, their usage seems pretty similar to MongoDB only. But storing user information can only be supported in PG or MongoDB. bl.ocks.org were also using MongoDB for authentication and elasticsearch for searching.
So I am still unsure how searching will happen when things are stored across two collections in elasticsearch DB(here users and gist).
Blocks was able to do it since it had the user id as the GitHub handle itself so it simply requested GitHub api for its gist. But in our case, I am planning to have a custom user_id which will be unique. This will ensure extending this platform in a way that the code of visualizations can also be stored somewhere else than just GitHub gist.
Having a user model will help us extend the platform. Otherwise, I guess we can just have one document for gist which will store the gist information and the user it is uploaded by. The latter case will require the user to be registered from one single platform only.

**Comment by domoritz** [comment]
I see. How about we go the simple route for now and only support github? Then we don't need to store the user and we don't need to do our own authentication. We hopefully can spin up a service in a month or so and then take it from there?

**Comment by algomaster99** [comment]
@domoritz okay ✌🏽 I will research a little about the ouath process as well. I think we would only need to create session variables on front-end when authenticated. Need not store anything more.

**Comment by siddhant1** [comment]
Instead of writing the whole authentication process ourselves , have a look at passport.js

**Comment by algomaster99** [comment]
@siddhant1 yeah, obviously. I was talking about the response given back by GitHub API after authentication. Will we need to story any relevant information from it?

**Comment by algomaster99** [comment]
We went for using GitHub gist as the database. :sweat_smile:
